
name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ]

# Tarefas a serem executadas
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      
      - name: Install dependencies
        run: npm install


      - name: Create .env file
        run: echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" > .env


      - name: Build project
        run: npm run build

      - name: Add my new Public Key to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: echo "${{ secrets.MY_PUBLIC_KEY }}" >> ~/.ssh/authorized_keys


      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/*" 
          target: "/home/${{ secrets.EC2_USERNAME }}/verificacao-aws"

      - name: Run final deploy script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo mv /home/${{ secrets.EC2_USERNAME }}/verificacao-aws/build/* /var/www/html/